name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-my-ielts
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install pnpm
        run: npm install -g pnpm@8.6.10

      - name: Verify pnpm
        run: pnpm --version

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies (pnpm)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "Found pnpm-lock.yaml, running pnpm install --frozen-lockfile"
            pnpm install --frozen-lockfile
          else
            echo "No pnpm-lock.yaml found, running pnpm install"
            pnpm install
          fi

      - name: Build
        run: pnpm run build --if-present

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

